// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	mspCfg "github.com/hyperledger/fabric-protos-go/msp"
	"github.com/hyperledger/fabric-sdk-go/pkg/common/providers/fab"
)

type ChannelCfg struct {
	IDStub        func() string
	iDMutex       sync.RWMutex
	iDArgsForCall []struct{}
	iDReturns     struct {
		result1 string
	}
	iDReturnsOnCall map[int]struct {
		result1 string
	}
	BlockNumberStub        func() uint64
	blockNumberMutex       sync.RWMutex
	blockNumberArgsForCall []struct{}
	blockNumberReturns     struct {
		result1 uint64
	}
	blockNumberReturnsOnCall map[int]struct {
		result1 uint64
	}
	MSPsStub        func() []*mspCfg.MSPConfig
	mSPsMutex       sync.RWMutex
	mSPsArgsForCall []struct{}
	mSPsReturns     struct {
		result1 []*mspCfg.MSPConfig
	}
	mSPsReturnsOnCall map[int]struct {
		result1 []*mspCfg.MSPConfig
	}
	AnchorPeersStub        func() []*fab.OrgAnchorPeer
	anchorPeersMutex       sync.RWMutex
	anchorPeersArgsForCall []struct{}
	anchorPeersReturns     struct {
		result1 []*fab.OrgAnchorPeer
	}
	anchorPeersReturnsOnCall map[int]struct {
		result1 []*fab.OrgAnchorPeer
	}
	OrderersStub        func() []string
	orderersMutex       sync.RWMutex
	orderersArgsForCall []struct{}
	orderersReturns     struct {
		result1 []string
	}
	orderersReturnsOnCall map[int]struct {
		result1 []string
	}
	VersionsStub        func() *fab.Versions
	versionsMutex       sync.RWMutex
	versionsArgsForCall []struct{}
	versionsReturns     struct {
		result1 *fab.Versions
	}
	versionsReturnsOnCall map[int]struct {
		result1 *fab.Versions
	}
	HasCapabilityStub        func(group fab.ConfigGroupKey, capability string) bool
	hasCapabilityMutex       sync.RWMutex
	hasCapabilityArgsForCall []struct {
		group      fab.ConfigGroupKey
		capability string
	}
	hasCapabilityReturns struct {
		result1 bool
	}
	hasCapabilityReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ChannelCfg) ID() string {
	fake.iDMutex.Lock()
	ret, specificReturn := fake.iDReturnsOnCall[len(fake.iDArgsForCall)]
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct{}{})
	fake.recordInvocation("ID", []interface{}{})
	fake.iDMutex.Unlock()
	if fake.IDStub != nil {
		return fake.IDStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.iDReturns.result1
}

func (fake *ChannelCfg) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *ChannelCfg) IDReturns(result1 string) {
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 string
	}{result1}
}

func (fake *ChannelCfg) IDReturnsOnCall(i int, result1 string) {
	fake.IDStub = nil
	if fake.iDReturnsOnCall == nil {
		fake.iDReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.iDReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *ChannelCfg) BlockNumber() uint64 {
	fake.blockNumberMutex.Lock()
	ret, specificReturn := fake.blockNumberReturnsOnCall[len(fake.blockNumberArgsForCall)]
	fake.blockNumberArgsForCall = append(fake.blockNumberArgsForCall, struct{}{})
	fake.recordInvocation("BlockNumber", []interface{}{})
	fake.blockNumberMutex.Unlock()
	if fake.BlockNumberStub != nil {
		return fake.BlockNumberStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.blockNumberReturns.result1
}

func (fake *ChannelCfg) BlockNumberCallCount() int {
	fake.blockNumberMutex.RLock()
	defer fake.blockNumberMutex.RUnlock()
	return len(fake.blockNumberArgsForCall)
}

func (fake *ChannelCfg) BlockNumberReturns(result1 uint64) {
	fake.BlockNumberStub = nil
	fake.blockNumberReturns = struct {
		result1 uint64
	}{result1}
}

func (fake *ChannelCfg) BlockNumberReturnsOnCall(i int, result1 uint64) {
	fake.BlockNumberStub = nil
	if fake.blockNumberReturnsOnCall == nil {
		fake.blockNumberReturnsOnCall = make(map[int]struct {
			result1 uint64
		})
	}
	fake.blockNumberReturnsOnCall[i] = struct {
		result1 uint64
	}{result1}
}

func (fake *ChannelCfg) MSPs() []*mspCfg.MSPConfig {
	fake.mSPsMutex.Lock()
	ret, specificReturn := fake.mSPsReturnsOnCall[len(fake.mSPsArgsForCall)]
	fake.mSPsArgsForCall = append(fake.mSPsArgsForCall, struct{}{})
	fake.recordInvocation("MSPs", []interface{}{})
	fake.mSPsMutex.Unlock()
	if fake.MSPsStub != nil {
		return fake.MSPsStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.mSPsReturns.result1
}

func (fake *ChannelCfg) MSPsCallCount() int {
	fake.mSPsMutex.RLock()
	defer fake.mSPsMutex.RUnlock()
	return len(fake.mSPsArgsForCall)
}

func (fake *ChannelCfg) MSPsReturns(result1 []*mspCfg.MSPConfig) {
	fake.MSPsStub = nil
	fake.mSPsReturns = struct {
		result1 []*mspCfg.MSPConfig
	}{result1}
}

func (fake *ChannelCfg) MSPsReturnsOnCall(i int, result1 []*mspCfg.MSPConfig) {
	fake.MSPsStub = nil
	if fake.mSPsReturnsOnCall == nil {
		fake.mSPsReturnsOnCall = make(map[int]struct {
			result1 []*mspCfg.MSPConfig
		})
	}
	fake.mSPsReturnsOnCall[i] = struct {
		result1 []*mspCfg.MSPConfig
	}{result1}
}

func (fake *ChannelCfg) AnchorPeers() []*fab.OrgAnchorPeer {
	fake.anchorPeersMutex.Lock()
	ret, specificReturn := fake.anchorPeersReturnsOnCall[len(fake.anchorPeersArgsForCall)]
	fake.anchorPeersArgsForCall = append(fake.anchorPeersArgsForCall, struct{}{})
	fake.recordInvocation("AnchorPeers", []interface{}{})
	fake.anchorPeersMutex.Unlock()
	if fake.AnchorPeersStub != nil {
		return fake.AnchorPeersStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.anchorPeersReturns.result1
}

func (fake *ChannelCfg) AnchorPeersCallCount() int {
	fake.anchorPeersMutex.RLock()
	defer fake.anchorPeersMutex.RUnlock()
	return len(fake.anchorPeersArgsForCall)
}

func (fake *ChannelCfg) AnchorPeersReturns(result1 []*fab.OrgAnchorPeer) {
	fake.AnchorPeersStub = nil
	fake.anchorPeersReturns = struct {
		result1 []*fab.OrgAnchorPeer
	}{result1}
}

func (fake *ChannelCfg) AnchorPeersReturnsOnCall(i int, result1 []*fab.OrgAnchorPeer) {
	fake.AnchorPeersStub = nil
	if fake.anchorPeersReturnsOnCall == nil {
		fake.anchorPeersReturnsOnCall = make(map[int]struct {
			result1 []*fab.OrgAnchorPeer
		})
	}
	fake.anchorPeersReturnsOnCall[i] = struct {
		result1 []*fab.OrgAnchorPeer
	}{result1}
}

func (fake *ChannelCfg) Orderers() []string {
	fake.orderersMutex.Lock()
	ret, specificReturn := fake.orderersReturnsOnCall[len(fake.orderersArgsForCall)]
	fake.orderersArgsForCall = append(fake.orderersArgsForCall, struct{}{})
	fake.recordInvocation("Orderers", []interface{}{})
	fake.orderersMutex.Unlock()
	if fake.OrderersStub != nil {
		return fake.OrderersStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.orderersReturns.result1
}

func (fake *ChannelCfg) OrderersCallCount() int {
	fake.orderersMutex.RLock()
	defer fake.orderersMutex.RUnlock()
	return len(fake.orderersArgsForCall)
}

func (fake *ChannelCfg) OrderersReturns(result1 []string) {
	fake.OrderersStub = nil
	fake.orderersReturns = struct {
		result1 []string
	}{result1}
}

func (fake *ChannelCfg) OrderersReturnsOnCall(i int, result1 []string) {
	fake.OrderersStub = nil
	if fake.orderersReturnsOnCall == nil {
		fake.orderersReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.orderersReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *ChannelCfg) Versions() *fab.Versions {
	fake.versionsMutex.Lock()
	ret, specificReturn := fake.versionsReturnsOnCall[len(fake.versionsArgsForCall)]
	fake.versionsArgsForCall = append(fake.versionsArgsForCall, struct{}{})
	fake.recordInvocation("Versions", []interface{}{})
	fake.versionsMutex.Unlock()
	if fake.VersionsStub != nil {
		return fake.VersionsStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.versionsReturns.result1
}

func (fake *ChannelCfg) VersionsCallCount() int {
	fake.versionsMutex.RLock()
	defer fake.versionsMutex.RUnlock()
	return len(fake.versionsArgsForCall)
}

func (fake *ChannelCfg) VersionsReturns(result1 *fab.Versions) {
	fake.VersionsStub = nil
	fake.versionsReturns = struct {
		result1 *fab.Versions
	}{result1}
}

func (fake *ChannelCfg) VersionsReturnsOnCall(i int, result1 *fab.Versions) {
	fake.VersionsStub = nil
	if fake.versionsReturnsOnCall == nil {
		fake.versionsReturnsOnCall = make(map[int]struct {
			result1 *fab.Versions
		})
	}
	fake.versionsReturnsOnCall[i] = struct {
		result1 *fab.Versions
	}{result1}
}

func (fake *ChannelCfg) HasCapability(group fab.ConfigGroupKey, capability string) bool {
	fake.hasCapabilityMutex.Lock()
	ret, specificReturn := fake.hasCapabilityReturnsOnCall[len(fake.hasCapabilityArgsForCall)]
	fake.hasCapabilityArgsForCall = append(fake.hasCapabilityArgsForCall, struct {
		group      fab.ConfigGroupKey
		capability string
	}{group, capability})
	fake.recordInvocation("HasCapability", []interface{}{group, capability})
	fake.hasCapabilityMutex.Unlock()
	if fake.HasCapabilityStub != nil {
		return fake.HasCapabilityStub(group, capability)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.hasCapabilityReturns.result1
}

func (fake *ChannelCfg) HasCapabilityCallCount() int {
	fake.hasCapabilityMutex.RLock()
	defer fake.hasCapabilityMutex.RUnlock()
	return len(fake.hasCapabilityArgsForCall)
}

func (fake *ChannelCfg) HasCapabilityArgsForCall(i int) (fab.ConfigGroupKey, string) {
	fake.hasCapabilityMutex.RLock()
	defer fake.hasCapabilityMutex.RUnlock()
	return fake.hasCapabilityArgsForCall[i].group, fake.hasCapabilityArgsForCall[i].capability
}

func (fake *ChannelCfg) HasCapabilityReturns(result1 bool) {
	fake.HasCapabilityStub = nil
	fake.hasCapabilityReturns = struct {
		result1 bool
	}{result1}
}

func (fake *ChannelCfg) HasCapabilityReturnsOnCall(i int, result1 bool) {
	fake.HasCapabilityStub = nil
	if fake.hasCapabilityReturnsOnCall == nil {
		fake.hasCapabilityReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.hasCapabilityReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *ChannelCfg) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	fake.blockNumberMutex.RLock()
	defer fake.blockNumberMutex.RUnlock()
	fake.mSPsMutex.RLock()
	defer fake.mSPsMutex.RUnlock()
	fake.anchorPeersMutex.RLock()
	defer fake.anchorPeersMutex.RUnlock()
	fake.orderersMutex.RLock()
	defer fake.orderersMutex.RUnlock()
	fake.versionsMutex.RLock()
	defer fake.versionsMutex.RUnlock()
	fake.hasCapabilityMutex.RLock()
	defer fake.hasCapabilityMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ChannelCfg) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fab.ChannelCfg = new(ChannelCfg)
