name: Security vulnerability scan

on:
  schedule:
    - cron: '20 02 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  go:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - govulncheck
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      - name: Scan
        run: make scan-go-${{ matrix.target }}
